### ISSUE TITLE
Help / How to install on ubuntu ?

### ISSUE THREAD

**Issue by rmcginnis** [VictorBersy/eve-online-killboard-to-slack#3]
Hello - 

   I was hoping if I may get some help with some how to or a quick guide on the commands to install this so i can get it working with my corps slack 

Clone the repository
Install ruby
bundle install at the root of the repo         

thanks,
Ronnie

**Comment by VictorBersy** [comment]
Hey Ronnie, 

Which version of Ubuntu do you have? Ruby? 

Describe me your issue, what did you try, etc...

**Comment by rmcginnis** [comment]
I have ubuntu 16.04 and not sure which ver of ruby ... how do i install ruby on my fresh new ubuntu server?

**Comment by rmcginnis** [comment]
@VictorBersy  -  I havent tried anything yet, because I'm new to ubuntu and command line cmds... So,  I was wondering how I do clone your repro on my ubuntu server?

**Comment by VictorBersy** [comment]
I'm sorry but I can't provide you the skills to learn CLI and how to setup a server.
I can help you if you have issues to run the project only.

Here's some ressources : 

* https://rvm.io/ to install Ruby
* https://help.github.com/articles/cloning-a-repository/ Cloning a repository 

Good luck!

**Comment by rmcginnis** [comment]
I have the server setup,  I'm just looking for the commands to use to install your project .. 

I have ubuntu 16.04 already
I have slack already

I was just looking for a guide on the steps to take to install your project on my server so it can post to my slack channel.
